-- Atlas Candlestick Knowledge Layer v1
-- Seed: Candlestick Concepts  
-- 19 Patterns: 8 Single, 7 Double, 4 Triple
-- Created: June 2026

-- SINGLE CANDLE PATTERNS (8)
INSERT INTO candlestick_concepts (candle_name, category, bullish_bearish_neutral, plain_english_meaning, psychological_interpretation, why_it_forms, confirmation_rules, invalidation_rules, expected_next_behavior, larger_pattern_role, shape_definition) VALUES
('Doji', 'single', 'neutral', 'A candle where open and close prices are equal or nearly equal', 'Market equilibrium', 'Balanced buying/selling', 'Body <5% range, shadows >=2x body', 'Body >10% range', 'Reversal within 1-3 candles', 'Pivot point', 'Body<5% range, shadows>=2x body'),
('Long-legged doji', 'single', 'neutral', 'Doji with very long shadows', 'Maximum uncertainty', 'Exhaustion after strong trend', 'Body<5%, shadows>=3x, range>=150% avg', 'Range<avg', 'Strong reversal in 1-2 candles', 'Volatility contraction', 'Body<5%, shadows>=3x, range>=150% avg'),
('Hammer', 'single', 'bullish', 'Small body at top, long lower shadow in downtrend', 'Bulls regained control', 'Support emerges after decline', 'Lower shadow>=2x body, body upper 25%', 'Upper shadow>lower', 'Bullish reversal in 2-3 candles', 'Bottoming signal', 'Lower shadow>=2x body, body upper 25%'),
('Inverted hammer', 'single', 'bullish', 'Small body at bottom, long upper shadow in downtrend', 'Buyers test resistance', 'Buying attempt rejected', 'Upper shadow>=2x body, body lower 25%', 'Lower shadow>upper', 'Bullish reversal in 2-3 candles', 'Bottoming signal', 'Upper shadow>=2x body, body lower 25%'),
('Shooting star', 'single', 'bearish', 'Small body at bottom, long upper shadow in uptrend', 'Sellers regained control', 'Selling emerges at resistance', 'Upper shadow>=2x body, body lower 25%', 'Lower shadow>upper', 'Bearish reversal in 2-3 candles', 'Topping signal', 'Upper shadow>=2x body, body lower 25%'),
('Hanging man', 'single', 'bearish', 'Small body at top, long lower shadow in uptrend', 'Sellers test support', 'Selling attempt rejected', 'Lower shadow>=2x body, body upper 25%', 'Upper shadow>lower', 'Bearish reversal in 2-3 candles', 'Topping signal', 'Lower shadow>=2x body, body upper 25%'),
('Marubozu', 'single', 'neutral', 'No shadows, full body', 'Complete control by one side', 'Strong directional move', 'No shadows <5% range', 'Any shadow >5%', 'Trend continuation', 'Momentum signal', 'No shadows, body=100% range'),
('Spinning top', 'single', 'neutral', 'Small body center, equal shadows', 'Indecision with volatility', 'Consolidation period', 'Body<25%, shadows>=body, balanced', 'Body>30%', 'Indecision or breakout', 'Consolidation', 'Body<25%, shadows>=body');

-- DOUBLE CANDLE PATTERNS (7)
INSERT INTO candlestick_concepts (candle_name, category, bullish_bearish_neutral, plain_english_meaning, psychological_interpretation, why_it_forms, confirmation_rules, invalidation_rules, expected_next_behavior, larger_pattern_role, shape_definition) VALUES
('Bullish engulfing', 'double', 'bullish', 'Small candle engulfed by larger bullish candle', 'Bulls overwhelm bears', 'Reversal after downtrend', '2nd engulfs 1st body, opens lower, closes higher', 'No full engulfment', 'Bullish reversal in 2-3 candles', 'Strong reversal', '2nd: bullish, open<1st close, close>1st open'),
('Bearish engulfing', 'double', 'bearish', 'Small candle engulfed by larger bearish candle', 'Bears overwhelm bulls', 'Reversal after uptrend', '2nd engulfs 1st body, opens higher, closes lower', 'No full engulfment', 'Bearish reversal in 2-3 candles', 'Strong reversal', '2nd: bearish, open>1st close, close<1st open'),
('Inside bar', 'double', 'neutral', '2nd candle range within 1st candle range', 'Consolidation, trend losing momentum', 'Compression before move', '2nd high<1st high AND 2nd low>1st low', 'Equal high/low', 'Breakout in 2-3 candles', 'Consolidation', '2nd: high<1st high, low>1st low'),
('Outside bar', 'double', 'neutral', '2nd candle range engulfs 1st candle range', 'Volatility expansion', 'Market gaining strength', '2nd high>1st high AND 2nd low<1st low', 'Equal high/low', 'Continuation of move', 'Momentum', '2nd: high>1st high, low<1st low'),
('Harami', 'double', 'neutral', '2nd candle body within 1st candle body', 'Trend losing momentum', 'Indecision after strong move', '2nd body within 1st body', 'Body extends beyond', 'Reversal in 2-3 candles', 'Reversal signal', '2nd body within 1st body'),
('Tweezer top', 'double', 'bearish', 'Equal highs, 2nd candle bearish', 'Sellers reject resistance', 'Failed breakout at resistance', 'Highs within 1%, 2nd bearish, uptrend', 'Highs differ >1%', 'Bearish reversal in 2-3 candles', 'Resistance rejection', '|high1-high2|<=1%, 2nd bearish'),
('Tweezer bottom', 'double', 'bullish', 'Equal lows, 2nd candle bullish', 'Buyers reject support', 'Failed breakdown at support', 'Lows within 1%, 2nd bullish, downtrend', 'Lows differ >1%', 'Bullish reversal in 2-3 candles', 'Support rejection', '|low1-low2|<=1%, 2nd bullish');

-- TRIPLE CANDLE PATTERNS (4)
INSERT INTO candlestick_concepts (candle_name, category, bullish_bearish_neutral, plain_english_meaning, psychological_interpretation, why_it_forms, confirmation_rules, invalidation_rules, expected_next_behavior, larger_pattern_role, shape_definition) VALUES
('Morning star', 'triple', 'bullish', 'Large bearish, small, large bullish closing above midpoint', 'Bullish reversal pattern', 'Bottoming after downtrend', '1st bearish, 2nd small, 3rd bullish close>1st midpoint', '3rd does not close above midpoint', 'Strong bullish reversal in 3-5 candles', 'Strong bottoming', '1st: bearish, 2nd: small, 3rd: bullish close>midpoint'),
('Evening star', 'triple', 'bearish', 'Large bullish, small, large bearish closing below midpoint', 'Bearish reversal pattern', 'Topping after uptrend', '1st bullish, 2nd small, 3rd bearish close<1st midpoint', '3rd does not close below midpoint', 'Strong bearish reversal in 3-5 candles', 'Strong topping', '1st: bullish, 2nd: small, 3rd: bearish close<midpoint'),
('Three white soldiers', 'triple', 'bullish', 'Three consecutive long bullish candles', 'Sustained bullish momentum', 'Strong uptrend continuation', '3 bullish, ascending closes, opens within bodies', 'Any bearish candle', 'Continuation for 3-5 candles', 'Trend continuation', '3 bullish, ascending, opens within bodies'),
('Three black crows', 'triple', 'bearish', 'Three consecutive long bearish candles', 'Sustained bearish momentum', 'Strong downtrend continuation', '3 bearish, descending closes, opens within bodies', 'Any bullish candle', 'Continuation for 3-5 candles', 'Trend continuation', '3 bearish, descending, opens within bodies');