-- Atlas Candlestick Knowledge Layer v1
-- Seed: Detection Rules
-- Machine-executable pattern detection for all 19 patterns
-- Created: June 2026

-- SINGLE CANDLE PATTERNS
INSERT INTO candlestick_detection_rules (candle_name, rule_expression, required_conditions, optional_conditions, timeframe, version) VALUES
('Doji', 'body_pct < 0.05 AND upper_shadow >= 2 * body AND lower_shadow >= 2 * body', 'body = ABS(close - open); range = high - low; body_pct = body / range; upper_shadow = high - MAX(open, close); lower_shadow = MIN(open, close) - low', 'range >= avg_range_20', 'daily', 1),
('Long-legged doji', 'body_pct < 0.05 AND upper_shadow >= 3 * body AND lower_shadow >= 3 * body AND range >= 1.5 * avg_range_20', 'body = ABS(close - open); range = high - low; body_pct = body / range; upper_shadow = high - MAX(open, close); lower_shadow = MIN(open, close) - low', 'range >= 2 * avg_range_20', 'daily', 1),
('Hammer', 'lower_shadow >= 2 * body AND body_position <= 0.25 AND prior_trend = ''down''', 'body = ABS(close - open); range = high - low; lower_shadow = MIN(open, close) - low; body_position = (MIN(open, close) - low) / range; prior_trend = CASE WHEN close < LAG(close, 1) OVER w AND LAG(close, 1) < LAG(close, 2) OVER w THEN ''down'' ELSE ''other'' END, w AS (PARTITION BY ticker ORDER BY timestamp)', 'upper_shadow <= 0.25 * body AND volume > avg_volume_20', 'daily', 1),
('Inverted hammer', 'upper_shadow >= 2 * body AND body_position >= 0.75 AND prior_trend = ''down''', 'body = ABS(close - open); range = high - low; upper_shadow = high - MAX(open, close); body_position = (high - MAX(open, close)) / range; prior_trend = CASE WHEN close < LAG(close, 1) OVER w AND LAG(close, 1) < LAG(close, 2) OVER w THEN ''down'' ELSE ''other'' END, w AS (PARTITION BY ticker ORDER BY timestamp)', 'lower_shadow <= 0.25 * body AND volume > avg_volume_20', 'daily', 1),
('Shooting star', 'upper_shadow >= 2 * body AND body_position >= 0.75 AND prior_trend = ''up''', 'body = ABS(close - open); range = high - low; upper_shadow = high - MAX(open, close); body_position = (high - MAX(open, close)) / range; prior_trend = CASE WHEN close > LAG(close, 1) OVER w AND LAG(close, 1) > LAG(close, 2) OVER w THEN ''up'' ELSE ''other'' END, w AS (PARTITION BY ticker ORDER BY timestamp)', 'lower_shadow <= 0.25 * body AND volume > avg_volume_20', 'daily', 1),
('Hanging man', 'lower_shadow >= 2 * body AND body_position <= 0.25 AND prior_trend = ''up''', 'body = ABS(close - open); range = high - low; lower_shadow = MIN(open, close) - low; body_position = (MIN(open, close) - low) / range; prior_trend = CASE WHEN close > LAG(close, 1) OVER w AND LAG(close, 1) > LAG(close, 2) OVER w THEN ''up'' ELSE ''other'' END, w AS (PARTITION BY ticker ORDER BY timestamp)', 'upper_shadow <= 0.25 * body AND volume > avg_volume_20', 'daily', 1),
('Marubozu', 'upper_shadow_pct < 0.05 AND lower_shadow_pct < 0.05', 'body = ABS(close - open); range = high - low; upper_shadow_pct = (high - MAX(open, close)) / range; lower_shadow_pct = (MIN(open, close) - low) / range', 'volume > avg_volume_20', 'daily', 1),
('Spinning top', 'body_pct < 0.25 AND upper_shadow >= body AND lower_shadow >= body AND ABS(upper_shadow - lower_shadow) <= 0.3 * MAX(upper_shadow, lower_shadow)', 'body = ABS(close - open); range = high - low; body_pct = body / range; upper_shadow = high - MAX(open, close); lower_shadow = MIN(open, close) - low', 'range >= avg_range_20', 'daily', 1);

-- DOUBLE CANDLE PATTERNS
INSERT INTO candlestick_detection_rules (candle_name, rule_expression, required_conditions, optional_conditions, timeframe, version) VALUES
('Bullish engulfing', 'c2 > c1 AND o2 < c1 AND c2 > o1 AND (c2 - o2) > ABS(o1 - c1)', 'o1 = open of candle 1, c1 = close of candle 1, o2 = open of candle 2, c2 = close of candle 2; prior_trend = CASE WHEN c1 < LAG(c1) OVER (PARTITION BY ticker ORDER BY timestamp) THEN ''down'' ELSE ''other'' END', 'prior_trend = ''down'' AND v2 > avg_volume_20', 'daily', 1),
('Bearish engulfing', 'c2 < c1 AND o2 > c1 AND c2 < o1 AND (o2 - c2) > ABS(c1 - o1)', 'o1 = open of candle 1, c1 = close of candle 1, o2 = open of candle 2, c2 = close of candle 2; prior_trend = CASE WHEN c1 > LAG(c1) OVER (PARTITION BY ticker ORDER BY timestamp) THEN ''up'' ELSE ''other'' END', 'prior_trend = ''up'' AND v2 > avg_volume_20', 'daily', 1),
('Inside bar', 'h2 < h1 AND l2 > l1', 'o1 = open of candle 1, h1 = high of candle 1, l1 = low of candle 1, c1 = close of candle 1, o2 = open of candle 2, h2 = high of candle 2, l2 = low of candle 2, c2 = close of candle 2', '(h1 - l1) >= avg_range_20', 'daily', 1),
('Outside bar', 'h2 > h1 AND l2 < l1', 'o1 = open of candle 1, h1 = high of candle 1, l1 = low of candle 1, c1 = close of candle 1, o2 = open of candle 2, h2 = high of candle 2, l2 = low of candle 2, c2 = close of candle 2', 'v2 > avg_volume_20', 'daily', 1),
('Harami', '(o2 > o1 AND c2 < c1 AND o2 < c1 AND c2 > o1) OR (o2 < o1 AND c2 > c1 AND o2 > c1 AND c2 < o1)', 'o1 = open of candle 1, c1 = close of candle 1, o2 = open of candle 2, c2 = close of candle 2; body1 = ABS(c1 - o1); body2 = ABS(c2 - o2); body2 < body1', 'body2 < 0.5 * body1', 'daily', 1),
('Tweezer top', 'ABS(h1 - h2) <= 0.01 * MAX(h1, h2) AND c2 < o2 AND prior_trend = ''up''', 'o1 = open of candle 1, h1 = high of candle 1, c1 = close of candle 1, o2 = open of candle 2, h2 = high of candle 2, c2 = close of candle 2; prior_trend = CASE WHEN c1 > LAG(c1) OVER (PARTITION BY ticker ORDER BY timestamp) THEN ''up'' ELSE ''other'' END', 'c2 < c1 AND v2 > avg_volume_20', 'daily', 1),
('Tweezer bottom', 'ABS(l1 - l2) <= 0.01 * MAX(l1, l2) AND c2 > o2 AND prior_trend = ''down''', 'o1 = open of candle 1, h1 = high of candle 1, l1 = low of candle 1, c1 = close of candle 1, o2 = open of candle 2, l2 = low of candle 2, c2 = close of candle 2; prior_trend = CASE WHEN c1 < LAG(c1) OVER (PARTITION BY ticker ORDER BY timestamp) THEN ''down'' ELSE ''other'' END', 'c2 > c1 AND v2 > avg_volume_20', 'daily', 1);

-- TRIPLE CANDLE PATTERNS
INSERT INTO candlestick_detection_rules (candle_name, rule_expression, required_conditions, optional_conditions, timeframe, version) VALUES
('Morning star', 'c1 < o1 AND body2 < 0.5 * avg_body_20 AND l2 < l1 AND c3 > o3 AND c3 > (o1 + c1) / 2', 'o1=open1,h1=high1,l1=low1,c1=close1,o2=open2,h2=high2,l2=low2,c2=close2,o3=open3,c3=close3; body2=ABS(c2-o2); avg_body_20=AVG(ABS(close-open)) OVER (PARTITION BY ticker ORDER BY timestamp ROWS 20 PRECEDING); prior_trend=CASE WHEN c1<LAG(c1) OVER w AND LAG(c1)<LAG(c1,2) OVER w THEN ''down'' ELSE ''other'' END, w AS (PARTITION BY ticker ORDER BY timestamp)', 'prior_trend = ''down'' AND v3 > avg_volume_20', 'daily', 1),
('Evening star', 'c1 > o1 AND body2 < 0.5 * avg_body_20 AND h2 > h1 AND c3 < o3 AND c3 < (o1 + c1) / 2', 'o1=open1,h1=high1,l1=low1,c1=close1,o2=open2,h2=high2,l2=low2,c2=close2,o3=open3,c3=close3; body2=ABS(c2-o2); avg_body_20=AVG(ABS(close-open)) OVER (PARTITION BY ticker ORDER BY timestamp ROWS 20 PRECEDING); prior_trend=CASE WHEN c1>LAG(c1) OVER w AND LAG(c1)>LAG(c1,2) OVER w THEN ''up'' ELSE ''other'' END, w AS (PARTITION BY ticker ORDER BY timestamp)', 'prior_trend = ''up'' AND v3 > avg_volume_20', 'daily', 1),
('Three white soldiers', 'c1 > o1 AND c2 > o2 AND c3 > o3 AND c2 > c1 AND c3 > c2 AND o2 > o1 AND o2 < c1 AND o3 > o2 AND o3 < c2', 'o1=open1,c1=close1,o2=open2,c2=close2,o3=open3,c3=close3; body1=ABS(c1-o1); body2=ABS(c2-o2); body3=ABS(c3-o3); avg_body_20=AVG(ABS(close-open)) OVER (PARTITION BY ticker ORDER BY timestamp ROWS 20 PRECEDING)', 'body1 > 0.5 * avg_body_20 AND body2 > 0.5 * avg_body_20 AND body3 > 0.5 * avg_body_20 AND v1 > avg_volume_20 AND v2 > avg_volume_20 AND v3 > avg_volume_20', 'daily', 1),
('Three black crows', 'c1 < o1 AND c2 < o2 AND c3 < o3 AND c2 < c1 AND c3 < c2 AND o2 < o1 AND o2 > c1 AND o3 < o2 AND o3 > c2', 'o1=open1,c1=close1,o2=open2,c2=close2,o3=open3,c3=close3; body1=ABS(c1-o1); body2=ABS(c2-o2); body3=ABS(c3-o3); avg_body_20=AVG(ABS(close-open)) OVER (PARTITION BY ticker ORDER BY timestamp ROWS 20 PRECEDING)', 'body1 > 0.5 * avg_body_20 AND body2 > 0.5 * avg_body_20 AND body3 > 0.5 * avg_body_20 AND v1 > avg_volume_20 AND v2 > avg_volume_20 AND v3 > avg_volume_20', 'daily', 1);