-- 0039_intraday_learning_tables.sql
-- Atlas Intraday Adaptive Learning Loop v1

-- Win/loss attribution per setup type: which conditions separate winners from losers
CREATE TABLE IF NOT EXISTS intraday_setup_attribution (
    id              BIGSERIAL        PRIMARY KEY,
    setup_type      TEXT             NOT NULL,
    direction       TEXT             NOT NULL,
    as_of_date      DATE             NOT NULL,
    condition_name  TEXT             NOT NULL,
    condition_type  TEXT             NOT NULL,   -- numeric | categorical | time
    winner_mean     DOUBLE PRECISION,
    loser_mean      DOUBLE PRECISION,
    difference      DOUBLE PRECISION,
    effect_size     DOUBLE PRECISION,            -- Cohen's d or lift ratio
    winner_n        INTEGER,
    loser_n         INTEGER,
    sample_size     INTEGER,
    p_value         DOUBLE PRECISION,
    confidence      DOUBLE PRECISION,            -- 1 - p_value
    UNIQUE (setup_type, direction, as_of_date, condition_name)
);
CREATE INDEX IF NOT EXISTS idx_iattr_setup_type  ON intraday_setup_attribution (setup_type, direction);
CREATE INDEX IF NOT EXISTS idx_iattr_as_of       ON intraday_setup_attribution (as_of_date DESC);
CREATE INDEX IF NOT EXISTS idx_iattr_effect_size ON intraday_setup_attribution (effect_size DESC);

-- Candidate refined rules generated by the adaptive learning loop
CREATE TABLE IF NOT EXISTS intraday_refined_rules (
    id                   BIGSERIAL        PRIMARY KEY,
    parent_setup_type    TEXT             NOT NULL,
    direction            TEXT             NOT NULL,
    rule_expression      TEXT             NOT NULL,   -- human-readable rule string
    added_conditions     JSONB,                       -- list of condition specs
    as_of_date           DATE             NOT NULL,
    -- IS metrics (original setup without filter)
    original_sample_size INTEGER,
    original_expectancy  DOUBLE PRECISION,
    original_pf          DOUBLE PRECISION,
    original_win_rate    DOUBLE PRECISION,
    -- IS metrics (refined = after applying added_conditions)
    refined_sample_size  INTEGER,
    refined_expectancy   DOUBLE PRECISION,
    refined_pf           DOUBLE PRECISION,
    refined_win_rate     DOUBLE PRECISION,
    -- OOS metrics (refined, out-of-sample)
    oos_sample_size      INTEGER,
    oos_expectancy       DOUBLE PRECISION,
    oos_pf               DOUBLE PRECISION,
    oos_win_rate         DOUBLE PRECISION,
    -- Walk-forward checks
    walk_forward_passed  BOOLEAN          DEFAULT FALSE,
    multi_ticker_breadth INTEGER,
    multi_week_breadth   INTEGER,
    outlier_sensitivity  DOUBLE PRECISION,           -- expectancy drop when largest trade removed
    -- Promotion decision
    status               TEXT             DEFAULT 'generated',
    reject_reason        TEXT,
    UNIQUE (parent_setup_type, direction, rule_expression, as_of_date)
);
CREATE INDEX IF NOT EXISTS idx_irr_setup_type  ON intraday_refined_rules (parent_setup_type, direction);
CREATE INDEX IF NOT EXISTS idx_irr_status      ON intraday_refined_rules (status);
CREATE INDEX IF NOT EXISTS idx_irr_as_of       ON intraday_refined_rules (as_of_date DESC);
CREATE INDEX IF NOT EXISTS idx_irr_oos_exp     ON intraday_refined_rules (oos_expectancy DESC NULLS LAST);
